broadcast-saves: false
broadcast-backups: true
strings:
  backup:
    start: Starting backup...
    end: Backup finished!
  save:
    start: Saving...
    end: Saved!
intervals:
  save: 5
  backup: 30
backups-on-file: 5
backup-directory: ./backup
backup-format: MM-dd-yyy.HH-mm.ss