name: Kabosu
version: @version@
main: com.x416.plugins.kabosu.Kabosu
authors: [Akoot]
description: World saver and settings backup
commands:
  kabosu:
    description: Kabosu!
    usage: /kabosu
    permission: kabosu.commands.kabosu
  task:
    description: Tasks!
    permission: kabosu.command.task
    usage: |
      /task create <name> <interval/delay> true|false
      /task delete|execute <name>